name: cloudrun-deploy
on:
  workflow_dispatch:
  push:   
   branches:
      - main
env:
  NODE_VERSION: 20.2.0
  IMAGE_NAME: gcr.io/weather-app-410220/weather-app
  CI: false
jobs:
  build--deploy-web-service:
    name: Build and deploy web service
    runs-on: ubuntu-latest
    steps:        
    - name: Checkout
      uses: actions/checkout@master    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'      
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'              
    # Setup GCloud
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'    
    - name: Configure Docker
      run: |
        gcloud auth configure-docker  
    # Build artifacts locally
    - name: use node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: https://registry.npmjs.org/ # Needed for auth
    - name: Build web assets
      working-directory: frontend
      run: |
        npm i
        CI=false npm run build
    - name: Build container and push to GCR
      run: |        
        docker build . -f ./Dockerfile --tag ${{env.IMAGE_NAME}}
        docker push ${{env.IMAGE_NAME}}      
    # Deploy the Docker image to cloud run
    - name: Deploy
      run: |
        gcloud run deploy weather-app --image ${{env.IMAGE_NAME}} \
        --platform managed \
        --region us-west2 \
        --port 4000 \
        --allow-unauthenticated \
        --memory 512M
